### ISSUE TITLE
Allow Swiss Standard German spellings in Search

### ISSUE THREAD

**Issue by ghost** [dadap/flingon-assister#22]
In Swiss Standard German, the sharp S (ß) is not used, being replaced by a double S. Ultimately, the search function on the German side of the app should return the corresponding words when the Swiss spellings are searched, which is currently does not do. 

Without knowing precisely what's going on under the hood when a search is performed, a first guess at a solution might be to replace all instances of "ss" in the user's query with something like (ss|ß) in the regex used for matching. 

Merci vilmal!

**Comment by dadap** [comment]
This should be possible if the Eszett is normalized to "ss" in the fields that are searched, and in the search query. The app already lowercases the definition field so that non-Klingon searches can be performed case insensitively. This field is not displayed to the user, so converting "ß" to "ss" should be harmless there. There are also "search tags" that are used to help find words using related words that aren't necessarily part of the official definition. These aren't displayed to the user, either, so they can also have "ß" converted to "ss". When the user makes a query, it should then be possible to locate words with Eszett regardless of whether it's spelled as "ß" or "ss". The query will be displayed to the user in whatever form it was entered; however, the result will always display as "ß". I'm assuming that wouldn't be a problem.

Luckily there is only a very small number of words in the database with ß.
